config/routes.rb
Qrp::Application.routes.draw do
root 'static_pages#home'
  get "password_resets/new"
  get "password_resets/edit"
  get "password_reset/new"
  get "password_reset/edit"

get '/goqrp' => redirect("https://www.qsl.net/n/nzqrpers/gqn/")
match '/about',   to: 'static_pages#about',   via: 'get'
resources :sessions, only: [:new, :create, :destroy]
match "/users/editgrid", :to => "users#editgrid", :via => "get"
match "/users/data", :to => "users#data", :as => "user_data", :via => "get"
match "/users/db_action", :to => "users#db_action", :as => "user_db_action", :via => "get"
resources :users
 get 'users/:id/add', to: 'users#add'
 get 'users/:id/delete', to: 'users#delete'

resources :topics
resources :qrpnzmembers
resources :hota
 get 'hota/:id/delete', to: 'hota#delete'
resources :posts
 get 'posts/:id/delete', to: 'posts#delete'
resources :images
 get 'images/:id/delete', to: 'images#delete'
resources :files
 get 'files/:id/delete', to: 'files#delete'
resources :uploadedfiles, path: "files"
 get 'uploadedfiles/:id/delete', to: 'files#delete'

  match '/sessions', to: 'static_pages#home',    via:'get'
  match '/queries/hut', to: 'queries#hut',    via:'get'
  match '/queries/park', to: 'queries#park',    via:'get'
  match '/queries/island', to: 'queries#island',    via:'get'
  match '/queries/summit', to: 'queries#summit',    via:'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signup',  to: 'users#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :password_resets, only: [:new, :create, :edit, :update]

match "/contest_logs/:id/save", :to => "contest_logs#save", :as => "contest_log_save_data", :via => "post"
match "/contest_logs/:id/load", :to => "contest_logs#load", :as => "contest_log_load_data", :via => "get"
resources :contest_logs
 get 'contest_logs/:id/delete', to: 'contest_logs#delete'
resources :uploads
resources :contest_series
resources :contests


end

app/models/topic.rb
class Topic < ActiveRecord::Base
def items
  items=Item.find_by_sql [ "select * from items where topic_id="+self.id.to_s+" order by updated_at desc" ]
end

def owner
  owner=User.find_by_id(self.owner_id)
end

def parent_topic
  item=Item.find_by_sql [" select * from items where item_type='topic' and item_id="+self.id.to_s ]
  if item and item.count>0 then
    topic=Topic.find_by_id(item.first.topic_id)
  end
  topic
end

def owner_callsign
  callsign=""
  if self.owner_id and self.owner then callsign =self.owner.callsign end
  callsign
end

def subscribed(user)
  subs=UserTopicLink.find_by_sql [ "select * from user_topic_links where user_id = "+user.id.to_s+" and topic_id = "+self.id.to_s ]
  if subs and subs.count>0 then true else false end
end

def url
  url=[self.id, self.name.parameterize].join('-')
end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

before_action :signed_in_user, only: [:destroy, :create, :update]

  def index
    @fulltopics=Topic.all.order(:name)
    @topics=@fulltopics.paginate(:per_page => 20, :page => params[:page])

  end

  def show
    id=params[:id].to_i
    @topic=Topic.find_by_id(id)
    if @topic then 
      @items=Item.find_by_sql [ "select * from items where topic_id="+id.to_s+" order by updated_at desc" ]
      if params[:title] then
        newitems=[]
        @items.each do |item|
          if item and item.end_item and item.end_item.title==params[:title] then newitems.push ( item ) end
        end
        @items=newitems
      end
      watchers=UserTopicLink.where(topic_id: id)
      @watch_count=watchers.count
   else
    flash[:error]="Sorry - the topic or post that you tried to view no longer exists"
    redirect_to '/'
   end
  end

  def new
    @parent_topic=Topic.find_by_id(params[:topic_id])
    @topic=Topic.new
  end

  def update
  if signed_in?  then
    id=params[:id].to_i
    @topic=Topic.find_by_id(id)
    if @topic and (current_user.is_admin or (current_user.id==@topic.owner_id)) then
       if params[:commit]=="Delete Topic" then
         #delete all item
         @items=Item.where(:topic_id => @topic.id)
         count=0
         if @items then @items.each do |item|
           if item.end_item then item.end_item.destroy end
           if item then item.destroy end
           count=count+1
         end end
         if @topic.destroy
           flash[:success] = "Topic containing "+count.to_s+" posts deleted, id:"+id.to_s
           index()
           render 'index'
         else
           edit()
           render 'edit'
         end
       else
         @topic.assign_attributes(topic_params)
         @topic.updated_by_id=current_user.id
         if @topic.save then
           flash[:success] = "Topic details updated"

           # Handle a successful update.
           if params[:referring]=='index' then
             index()
             render 'index'
           else
             @items=@topic.items
             render 'show'
           end
         else
           render 'edit'
         end
       end #delete or edit
     else
       redirect_to '/'
     end # do we have permissions
    else
      redirect_to '/'
    end #does it exist
  end
  def edit
    if params[:referring] then @referring=params[:referring] end

    id=params[:id].to_i
    if(!(@topic = Topic.where(id: id).first))
      redirect_to '/'
    end
  end

  def create
    if signed_in? and current_user.is_modifier then
      if params[:topic_id] then @parent_topic=Topic.find_by_id(params[:topic_id]) end

      @topic=Topic.new(topic_params)

      @topic.created_by_id = current_user.id #current_user.id
      @topic.updated_by_id = current_user.id #current_user.id
      @topic.last_updated = Time.now

      if @topic.save
        if @parent_topic then
          item=Item.new
          item.topic_id=@parent_topic.id
          item.item_type="topic"
          item.item_id=@topic.id
          item.save
        end

        flash[:success] = "New topic added, id:"+@topic.id.to_s
        @edit=true

      #render edit panel to allow user to add links (can't do in create)
        @id=@topic.id
        params[:id]=@id.to_s
        show()
        render 'show'
      else
        flash[:error] = "Error creating topic"
        @edit=true
        render 'new'
      end
    else
      redirect_to '/'
    end

  end

  def destroy
  end

  private
  def topic_params
    params.require(:topic).permit(:name, :description, :owner_id, :is_owners, :is_public, :is_members_only, :date_required, :duration_required, :allow_mail, :is_spot, :is_alert)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_editgrid.html.erb
<div id="actionbar" class="span7">
   <div id="crumbs">
     <%=link_to "Home", '/', remote: true,  :id => 'home', :onclick => "linkHandler('home')" %>
     &nbsp;--&gt;&nbsp;
     <%=  link_to  "Huts:", '/huts', remote: true,  :id => 'huts', :onclick => "linkHandler('huts')" %>
     &nbsp;--&gt;&nbsp;
     <b>Edit Table</b>
     </div>
   <div id="controls">
       <%=  link_to "View Table", '/huts/', class: "btn btn-small btn-primary", remote: true, :id => 'huts', :onclick => "linkHandler('huts')" %>
       <% if current_user.is_admin %>
            <input type="button" class= "btn btn-small btn-primary" value="Delete Row" onclick="grid.deleteSelectedRows()" />
       <% end %>
       <%=  link_to "Download", '/huts.csv', class: "btn btn-small btn-primary"%>
       <%=  link_to "Show/Hide Map", "#", class: "btn btn-small btn-primary",   :onclick => "toggle_map(); return false;"%>
   </div>
</div>

<div id="right_scroll">
   <%= render 'flash' %>
   <div id="grid_here" style="width: 100%; height: calc(100% - 72px); position: fixed"></div>
</div>
<script type="text/javascript" charset="UTF-8">
     map_smaller();
     var grid = new dhtmlXGridObject("grid_here");
     grid.setImagePath("/assets/imgs/");
     grid.setHeader("Id, Name, Description,X,Y,altitude,DOC?,Active?,DOC Link, Hutbagger Link, Tramper Link, Routeguides Link, General Link");
     grid.attachHeader("#,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter");
     grid.setColSorting("int,str,str,int,int,int,str,str,str,str,str,str,str");
     grid.setColTypes("ro,ed,ed,edn,edn,edn,ch,ch,ed,ed,ed,ed,ed");
     grid.setInitWidths("60,100,200,100,100,60,60,60,100,100,100,100,100");

     grid.setSkin("dhx_skyblue");
     grid.init();
     grid.load("<%= hut_data_path %>", "json");
     dp = new dataProcessor("<%= hut_db_action_path %>");
     dp.setTransactionMode("GET",false);
     dp.init(grid);

    if(map_size==0) { 
       $('#actionbar').removeClass('span7');
       $('#actionbar').addClass('span12');
    }

</script>

app/views/topics/_hota_details.html.erb
 <div class="bordered_box">
   <div class="box_header">
      <p><%=@contact.title%> <i><%=link_to "View", "http://"+@contact.url, class: 'link_to'%>
      <% if current_user and current_user.is_admin then %>
        <%= link_to "Delete", '/hota/'+@contact.id.to_s+'/delete', confirm: "Delete post: Are you sure?", class: 'link_to' %>
      <% end %>
      </i> </p>
  </div>
 </div>

app/views/topics/_index.html.erb
<script>
$(function () {
  $('#right_panel .pagination a').on('click', function () {
    $.getScript(this.href);
    return false;
  });
});

</script>

%>
<div id="actionbar" class="span12">
   <div id="crumbs">
     <%=link_to "Home", '/'%>
     &nbsp;--&gt;&nbsp;
     <b>Topics</b>
   </div>
   <div id="controls">
       <% if current_user and current_user.is_modifier %>
          <%=  link_to "Add Topic", '/topics/new', class: "btn btn-small btn-primary" %>
       <% end %>
   </div>
</div>
<div id="left_panel">
   <%=render 'layouts/left_panel'%>
</div>
<div id="right_panel">

<div id="right_scroll">

  <% if @topics %>
    <div class="name_pagination"> <%= will_paginate(@topics) %></div>
    <% count=0%>
    <% @topics.each do |topic| %>
       <div class="erow"><div class="sectiontitle">
         <%= link_to topic.name, '/topics/'+topic.url%>
       </div></div>
         <div class="erow"><div style="padding-left:10px;padding-top:6px"><%=raw topic.description%></div></div>

         <% if (topic.items.count>0)  %>
             <div style="padding-left:10px">
               <% item=topic.items.first %>
               <%#=render :partial => 'topics/item_details',  :locals => {:item => item, :topic=>@topic} %>
             </div>
         <% end %>

         <div class="hrline">
            <hr noshade size="4">
         </div>

       <% count+=1%>
    <% end %>
    <div class="erow"><div class="name_pagination"> <%= will_paginate(@topics) %></div></div>

  <% end %>
</div>
</div>

app/views/topics/_item_details.html.erb
<% if item.item_type=="post" then %>
  <% @post=item.post %>
  <%=if @post then render 'posts/post_details' end%>
<% elsif item.item_type=="image" then %>
  <% @image=item.image %>
  <%=if @image then render 'images/image_details' end%>
<% elsif item.item_type=="file" then %>
  <% @uploadedfile=item.file %>
  <%=if @uploadedfile then render 'files/file_details' end%>
<% elsif item.item_type=="hota" then %>
  <% @contact=HotaPost.find_by_id(item.item_id) %>
  <%=if @contact then  render 'topics/hota_details' end %>
<% elsif item.item_type=="topic" then %>
  <% puts "got subtopic" %>
  <% @subtopic=item.subtopic %>
  <%=if @subtopic then render 'topics/topic_details' end%>
<% end %>

app/views/topics/_topic_details.html.erb
 <div class="bordered_box">
   <div class="box_header">
      <p><div class="sectiontitle">--&gt Sub-Topic: <%= link_to @subtopic.name, '/topics/'+@subtopic.id.to_s%></div>
      </p>
      <p>
      <%= link_to @subtopic.owner.callsign, '/users/'+@subtopic.owner.callsign %>
      <% if current_user and (current_user.id==@subtopic.created_by_id or current_user.is_admin) then %>
        <u><i><%=  link_to "Edit", '/topics/'+@subtopic.id.to_s+'/edit'%></i></u>
        <u><i><%= link_to "Delete", '/topics/'+@subtopic.id.to_s+'/delete', confirm: "Delete topic: Are you sure?" %></i></u>
      <% end %>
      </p>
   </div>
   <div class="box_contents">
      <div class="sectiontext"><%=raw (@subtopic.description).gsub(/(?<=<style type=\"text\/css\">).+(?=<\/style>)/m,'')%></div>
   </div>
 </div>

app/views/topics/_topic_form.html.erb
<script type="text/javascript">
//<![CDATA[
   bkLib.onDomLoaded(startEdit);

function startEdit() {
  nicEditors.allTextAreas();
  init();
}

</script>

<div class="fullform">
   <%= form_for(@topic) do |f| %>
     <% if @parent_topic then %> 
       <%=hidden_field_tag(:topic_id, @parent_topic.id)%>
     <% end %> 
     <div id="actionbar-form" class="span12">
       <div id="crumbs">
         <%=link_to "Home", '/'%>
         &nbsp;--&gt;&nbsp;
         <%=  link_to  "Topics", '/topics'%>
         &nbsp;--&gt;&nbsp;
         <%if @topic.id%>
            <b><%=link_to @topic.name, '/topics/'+@topic.url%></b>
            &nbsp;--&gt;&nbsp;
            <b>Edit</b>
         <% else %>
            <b>New</b>
         <% end %>

       </div>

       <div id="controls">
          <%= f.submit @submit_button, class: "btn btn-small btn-primary btn-highlight" %>
          <% if @topic.id %><% if params[:referring]=='index'%>
            <%=  link_to "Cancel", '/topics', class: "btn btn-small btn-primary"%>
          <% else %>
            <%=  link_to "Cancel", '/topics/'+@topic.url, class: "btn btn-small btn-primary"%>
          <% end %> <% end %>

          <%  if(@submit_button == "Save Changes" and (current_user.is_admin or current_user.id==@topic.owner_id)) %>
            <%= f.submit "Delete Topic", confirm: "Delete entire topic: Are you sure?", class: "btn btn-small btn-primary", callsign: "delete", id:  "deletebutton" %>
          <% end %>

       </div>
     </div>

<div id="left_panel"  style="margin-top:0px !important">
   <%=render 'layouts/left_panel'%>
</div>
<div id="right_panel"  style="margin-top:0px !important">

     <%= render 'shared/error_messages' %>	

     <div id="right_scroll">

        <span>
          <%=f.label :name %>
          <%= f.text_field :name %>
        </span>
  
        <span>
          <%=f.label :owner_id, "Owner"%>
          <% if current_user and current_user.is_admin then %>
            <%= collection_select( :topic, :owner_id, User.all.order(:callsign), :id, :callsign, {}) %></td>
          <% else %>
            <%= collection_select( :topic, :owner_id, User.where(:id => current_user.id), :id, :callsign, {}) %></td>
          <% end %>
        </span>
  
        <%=f.label :desctiption%>
          <div id="editPanel"></div>
          <span id="descrSpan">
            <%= f.text_area :description %>
          </span>

        <span>
          <%= "Any user can post " %><br/>
          <%= f.check_box :is_public%><br/><br/>
        </span>

        <span>
          <%= "Only owner can post " %><br/>
          <%= f.check_box :is_owners%><br/><br/>
        </span>

        <span>
          <%= "Only visible to registered members " %><br/>
          <%= f.check_box :is_members_only%><br/><br/>
        </span>

        <span>
          <%= "Topic for alerts?"%>
          <%= f.check_box :is_alert%><br/><br/>
        </span>
        <span>
          <%= "Topic for spots?"%>
          <%= f.check_box :is_spot%><br/><br/>
        </span>
        <span>
          <%= "Allow members to subscribe to mails from this topic " %><br/>
          <%= f.check_box :allow_mail%><br/><br/>
        </span>
     </div>

  <% end %>
</div>
</div>

<script>
  startEdit();
</script>

app/views/topics/_topic_index.html.erb
<div id="right_scroll">
  <h2>Topics</h2>
 <br/>
  <% if @indextopics %>
    <% count=0%>
    <% @indextopics.each do |topic| %>
      <% if not topic.parent_topic then %>
        <%=render :partial => 'topics/topic_index_level',  :locals => {:topic => topic, :level => 0} %> 
      <% end %>
      <% count += 1 %>
    <% end %>
  <% end %>
</div>

app/views/topics/_topic_index_level.html.erb
        <% if topic then %>
        <div class="erow"><div class="sectiontitle">
          &gt; <%= link_to topic.name, '/topics/'+topic.url%><br/>
        </div></div>
        <div class="indent">
          <% if (topic.items.count>0)  %>
              <% count=0 %>
                 <% item=topic.items[count] %>
                 <% while item and item.item_type=="topic" %>
                   <% count=count+1 %>
                   <% item=topic.items[count] %>
                 <% end %>
              <% if item then %> 
                <%=render :partial => 'topics/item_summary',  :locals => {:item => item} %>
              <% end %>
              <% topic.items.each do |item| %>
                <% if item.item_type=="topic" then %>
                  <%=render :partial => 'topics/topic_index_level',  :locals => {:topic => item.end_item, :level => level+1} %> 
            
                <% end %>
              <% end %>
          <% end %>
         </div>
         <% end %>

app/views/topics/editgrid.js.erb
if (window.history.pushState!=null) window.history.pushState(null, '', '/huts/editgrid');
$('#right_panel').html("<%= escape_javascript(render(:partial => 'huts/editgrid')).html_safe %>");

app/views/topics/index.html.erb
<%= render 'topics/index' %>

app/views/topics/index.js.erb
if (window.history.pushState!=null) window.history.pushState(null, 'QRP.NZ | <%@mtitle%>', '/<%=@ptitle%>/<%=params[:id]%>');
$('#right_panel').html("<%= escape_javascript(render(:partial => 'topics/index')).html_safe %>");

app/views/topics/new.html.erb
<%= render 'topics/new' %>

app/views/topics/new.js.erb
if (window.history.pushState!=null) window.history.pushState(null, 'QRP.NZ | <%@mtitle%>', '/<%=@ptitle%>/<%=params[:id]%>');
$('#right_panel').html("<%= escape_javascript(render(:partial => 'topics/new')).html_safe %>");

app/views/topics/show.html.erb
<%= render 'topics/show' %>