config/routes.rb
Qrp::Application.routes.draw do
root 'static_pages#home'
  get "password_resets/new"
  get "password_resets/edit"
  get "password_reset/new"
  get "password_reset/edit"

get '/goqrp' => redirect("https://www.qsl.net/n/nzqrpers/gqn/")
match '/about',   to: 'static_pages#about',   via: 'get'
resources :sessions, only: [:new, :create, :destroy]
match "/users/editgrid", :to => "users#editgrid", :via => "get"
match "/users/data", :to => "users#data", :as => "user_data", :via => "get"
match "/users/db_action", :to => "users#db_action", :as => "user_db_action", :via => "get"
resources :users
 get 'users/:id/add', to: 'users#add'
 get 'users/:id/delete', to: 'users#delete'

resources :topics
resources :qrpnzmembers
resources :hota
 get 'hota/:id/delete', to: 'hota#delete'
resources :posts
 get 'posts/:id/delete', to: 'posts#delete'
resources :images
 get 'images/:id/delete', to: 'images#delete'
resources :files
 get 'files/:id/delete', to: 'files#delete'
resources :uploadedfiles, path: "files"
 get 'uploadedfiles/:id/delete', to: 'files#delete'

  match '/sessions', to: 'static_pages#home',    via:'get'
  match '/queries/hut', to: 'queries#hut',    via:'get'
  match '/queries/park', to: 'queries#park',    via:'get'
  match '/queries/island', to: 'queries#island',    via:'get'
  match '/queries/summit', to: 'queries#summit',    via:'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signup',  to: 'users#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :password_resets, only: [:new, :create, :edit, :update]

match "/contest_logs/:id/save", :to => "contest_logs#save", :as => "contest_log_save_data", :via => "post"
match "/contest_logs/:id/load", :to => "contest_logs#load", :as => "contest_log_load_data", :via => "get"
resources :contest_logs
 get 'contest_logs/:id/delete', to: 'contest_logs#delete'
resources :uploads
resources :contest_series
resources :contests


end

app/controllers/contest_series_controller.rb
class ContestSeriesController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :editgrid]

  def editgrid

  end

  def index_prep
    whereclause="true"
    if params[:filter] then
      @filter=params[:filter]
      whereclause="is_"+@filter+" is true"
    end

    @searchtext=params[:searchtext]
    if params[:searchtext] then
       whereclause=whereclause+" and lower(name) like '%%"+@searchtext.downcase+"%%'"
    end

    @contest_series=ContestSeries.find_by_sql [ 'select * from contest_series where '+whereclause+' order by name limit 100' ]
    counts=ContestSeries.find_by_sql [ 'select count(id) as id from contest_series where '+whereclause ]
    if counts and counts.first then @count=counts.first.id else @count=0 end
  end


  def index
    index_prep()
    respond_to do |format|
      format.html
      format.js
      format.csv { send_data contest_series_to_csv(@contest_series), filename: "contest_series-#{Date.today}.csv" }
    end
  end
  def show
    if(!(@contest_series = ContestSeries.find_by_id(params[:id].to_i)))
      redirect_to '/'
    end
  end

  def edit
    if params[:referring] then @referring=params[:referring] end

    if(!(@contest_series = ContestSeries.where(id: params[:id]).first))
      redirect_to '/'
    end
  end
  def new
    @contest_series = ContestSeries.new
    @contest_series.is_active=true
  end

 def create
    if signed_in? and current_user.is_modifier then

    @contest_series = ContestSeries.new(contest_series_params)
    @contest_series.createdBy_id=current_user.id

      if @contest_series.save
          @contest_series.reload
          if params[:referring]=='index' then
            index_prep()
            render 'index'
          else
            render 'show'
          end

      else
          render 'new'
      end
    else
      redirect_to '/'
    end
 end

def update
  if signed_in? and current_user.is_modifier then
    if params[:delete] then
      contest_series = ContestSeries.find_by_id(params[:id])
      if contest_series.contests and contest_series.contests.count>0 then
          flash[:error] = "ContestSeries contains contests. Cannot delete until contests have been deleted.  You could just set it to inactive to disable it but not delete."

          #tried to update a nonexistant hut
          render 'edit'
      else
        if contest_series and contest_series.destroy
          flash[:success] = "ContestSeries deleted, id:"+params[:id]
          index_prep()
          render 'index'
        else
          edit()
          render 'edit'
        end
      end
    else
      if(!@contest_series = ContestSeries.find_by_id(params[:id]))
          flash[:error] = "ContestSeries does not exist: "+@contest_series.id.to_s

          #tried to update a nonexistant hut
          render 'edit'
      end

      @contest_series.assign_attributes(contest_series_params)
      @contest_series.createdBy_id=current_user.id

      if @contest_series.save
        flash[:success] = "ContestSeries details updated"

        # Handle a successful update.
        if params[:referring]=='index' then
          index_prep()
          render 'index'
        else
          render 'show'
        end
      else
        render 'edit'
      end
    end
  else
    redirect_to '/'
  end
end

  def contest_series_params
    params.require(:contest_series).permit(:id, :name, :description, :start_date, :end_date, :include_valid, :include_qrp, :include_portable, :include_backcountry, :include_qth, :include_rst, :include_index, :include_freq, :members_only, :is_active, :base_points, :valid_points,  :qrp_points, :portable_points, :backcountry_points, :cw_points, :dx_points, :minreqs, :log_url, :xls_log_url, :odt_log_url, :score_per_hour)
  end

end

app/helpers/contest_series_helper.rb
module ContestSeriesHelper
end

app/views/contest_series/_edit.html.erb
<%  @submit_button = "Save Changes" %>
<%= render 'contest_series_form' %>

app/views/contest_series/_editgrid.html.erb
<div id="actionbar" class="span7">
   <div id="crumbs">
     <%=link_to "Home", '/', remote: true,  :id => 'home', :onclick => "linkHandler('home')" %>
     &nbsp;--&gt;&nbsp;
     <%=  link_to  "Parks:", '/parks', remote: true,  :id => 'parks', :onclick => "linkHandler('parks')" %>
     &nbsp;--&gt;&nbsp;
     <b>Edit Table</b>
     </div>
   <div id="controls">
       <%=  link_to "View Table", '/parks/', class: "btn btn-small btn-primary", remote: true, :id => 'parks', :onclick => "linkHandler('parks')" %>
       <% if current_user.is_admin %>
            <input type="button" class= "btn btn-small btn-primary" value="Delete Row" onclick="grid.deleteSelectedRows()" />
       <% end %>
       <%=  link_to "Download", '/parks.csv', class: "btn btn-small btn-primary"%>
       <%=  link_to "Show/Hide Map", "#", class: "btn btn-small btn-primary",   :onclick => "toggle_map(); return false;"%>
   </div>
</div>

<div id="right_scroll">
   <%= render 'flash' %>
   <div id="grid_here" style="width: 100%; height: calc(100% - 72px); position: fixed"></div>
</div>
<script type="text/javascript" charset="UTF-8">
     map_smaller();
     var grid = new dhtmlXGridObject("grid_here");
     grid.setImagePath("/assets/imgs/");
     grid.setHeader("Id, Name, Description,Minor?,Active?,DOC Link,Tramper Link,General Link");
     grid.attachHeader("#,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter,#text_filter");
     grid.setColSorting("int,str,str,str,str,str,str,str");
     grid.setColTypes("ro,ed,ed,ch,ch,ed,ed,ed");
     grid.setInitWidths("60,100,200,60,60,100,100,100");

     grid.setSkin("dhx_skyblue");
     grid.init();
     grid.load("<%= park_data_path %>", "json");
     dp = new dataProcessor("<%= park_db_action_path %>");
     dp.setTransactionMode("GET",false);
     dp.init(grid);

    if(site_map_size==0) { 
       $('#actionbar').removeClass('span7');
       $('#actionbar').addClass('span12');
    }

</script>

app/views/contest_series/_history_tree.html.erb
  <table class="places" id="tree-table">
    <tr>
      <th>Event</th>
      <th>Location</th>
      <th>Date</th>
      <th>Number</th>
      <th>Notes</th>
      <th>Action</th>
    </tr>
    <% count=0 %>
    <% collection_row=count %>
    <tr data-tt-id="<%=count%>" style="height: 34px;">
      <td>
        <% if current_person.is_modifier %>
          <span title="Click to edit"><%= link_to image_tag("/assets/pencil_edit.png", :class => 'dock-item'), '/collections/'+@collection.id.to_s+'/edit?referring=index', remote: true, onclick: "linkHandler('editbutton')", id:  "editbutton", alt: "Edit"  %></span>
        <% end %>

      <%= link_to "Collected: "+@collection.id.to_s, '/collections/'+@collection.id.to_s, remote: true, :id => 'collection_link_'+@collection.id.to_s, :onclick => "linkHandler('collection_link_"+@collection.id.to_s+"')" %>
      </td>
      <td><%if @collection.source then%>
            <%=link_to @collection.source.name, '/sources/'+@collection.source.id.to_s, remote: true, :id => 'collection_source_'+@collection.id.to_s, :onclick => "linkHandler('collection_source_"+@collection.id.to_s+"')" %>
          <% else %>
            <%=@collection.source_description%>
          <% end %></td>
      <td><%=if @collection.date then @collection.date.strftime('%d/%m/%Y') end%></td>
      <td><%=@collection.no_collected %></td>
      <td><%if @collection.notes and @collection.notes.length>0 %><div class="hoverover"><span title='<%=@collection.notes%>'><%=@collection.notes[0..8]+"..."%></span></div><%end%></td>
      <td><%=  link_to "Sow", '/seeds/new?source='+@collection.id.to_s, class: "btn btn-small btn-primary", style: "width: 28px;", remote: true, :onclick => "linkHandler('add')" %></td>
    </tr>


    <% if @collection and @collection.seeds then @collection.seeds.order("seed_code").each do |seed| %>    
      <% count+=1 %>
      <% seed_row=count %>
      <tr data-tt-id="<%=count%>" data-tt-parent-id="<%=collection_row%>"  style="height: 34px;">
        <td>
          <% if current_person.is_modifier %>
            <span title="Click to edit"><%= link_to image_tag("/assets/pencil_edit.png", :class => 'dock-item'), '/seeds/'+seed.id.to_s+'/edit?referring=index', remote: true, onclick: "linkHandler('editbutton')", id:  "editbutton", alt: "Edit"  %></span>
          <% end %>

        <%= link_to "Sown: "+seed.seed_code, '/seeds/'+seed.id.to_s, remote: true, :id => 'seed_link_'+seed.id.to_s, :onclick => "linkHandler('seed_link_"+seed.id.to_s+"')" %>
        </td>
        <td></td>
        <td><%=if seed.date_sown then seed.date_sown.strftime('%d/%m/%Y') end%></td>
        <td><%=seed.number_sown %></td>
        <td><%if seed.notes and seed.notes.length>0 %><div class="hoverover"><span title='<%=seed.notes%>'><%=seed.notes[0..8]+"..."%></span></div><%end%></td>
        <td><%=  link_to "Pot", '/seedlings/new?source='+seed.seed_code, class: "btn btn-small btn-primary", style: "width: 28px;", remote: true, :onclick => "linkHandler('add')" %></td>
      </tr>


      <% seed.seedlings.order("seedling_code").each do |seedling| %>
         <% count+=1%>
         <% seedling_row=count %>
         <tr data-tt-id="<%=count%>" data-tt-parent-id="<%=seed_row%>"  style="height: 34px;">
           <td>
              <% if current_person.is_modifier %>
                <span title="Click to edit"><%= link_to image_tag("/assets/pencil_edit.png", :class => 'dock-item'), '/seedlings/'+seedling.id.to_s+'/edit?referring=index', remote: true, onclick: "linkHandler('editbutton')", id:  "editbutton", alt: "Edit"  %></span>
              <% end %>
              <%= link_to "Potted: "+seedling.seedling_code, '/seedlings/'+seedling.id.to_s, remote: true, :id => 'seedling_link_'+seedling.id.to_s, :onclick => "linkHandler('seedling_link_"+seedling.id.to_s+"')" %>
           </td>
           <td></td>
           <td><%=if seedling.date_potted then seedling.date_potted.strftime('%d/%m/%Y') end%></td>
           <td><%=seedling.number_potted.to_s+"("+seedling.current_stock.to_s+")" %></td>
           <td><%if seedling.notes and seedling.notes.length>0 %><div class="hoverover"><span title='<%=seedling.notes%>'><%=seedling.notes[0..8]+"..."%></span></div><%end%></td>
           <td><%=  link_to "Plant", '/plantings/new?source='+seedling.seedling_code, class: "btn btn-small btn-primary", style: "width: 28px;", remote: true, :onclick => "linkHandler('add')" %></td>
         </tr> 

         <% seedling.plantings.order("planting_code").each do |planting| %>
           <% count+=1%>
           <% planting_row=count %>
           <tr data-tt-id="<%=count%>" data-tt-parent-id="<%=seedling_row%>"  style="height: 34px;">
             <td>
                <% if current_person.is_modifier %>
                  <span title="Click to edit"><%= link_to image_tag("/assets/pencil_edit.png", :class => 'dock-item'), '/plantings/'+planting.id.to_s+'/edit?referring=index', remote: true, onclick: "linkHandler('editbutton')", id:  "editbutton", alt: "Edit"  %></span>
                <% end %>
                <%= link_to "Planted: "+planting.planting_code, '/plantings/'+planting.id.to_s, remote: true, :id => 'planting_link_'+planting.id.to_s, :onclick => "linkHandler('planting_link_"+planting.id.to_s+"')" %>
             </td>
             <td>
               <%if planting.destination then %>
                 <%= link_to planting.destination.name, '/destinations/'+planting.destination.id.to_s, remote: true, :id => 'destination_link_'+planting.id.to_s, :onclick => "linkHandler('destination_link_"+planting.id.to_s+"')" %>
              <% else %>
                <div class="hoverover"><span title='<%=planting.dest_description%>'><%=planting.dest_description[0..15]+"..."%></span></div>
              <% end %>
             </td>
             <td><%=if planting.date_planted then planting.date_planted.strftime('%d/%m/%Y') end%></td>
             <td><%=planting.number_planted.to_s+"("+planting.number_survived.to_s+")" %></td>
             <td><%if planting.notes and planting.notes.length>0 %><div class="hoverover"><span title='<%=planting.notes%>'><%=planting.notes[0..8]+"..."%></span></div><%end%></td>
             <td></td>
           </tr>
         <% end %>
      <% end %>
    <% end end %>
</table>
<script>
$("#tree-table").treetable({ expandable: true, initialState: "expanded" });
</script>

app/views/contest_series/_index.html.erb
<div id="actionbar" class="span12">
   <div id="crumbs">
     <%=link_to "Home", '/' %>
     &nbsp;--&gt;&nbsp;
     <b>Contest</b>
     </div>
   <div id="controls">
       <% if current_user and current_user.is_admin %>
            <%=  link_to "Edit Table", '/contest_series/editgrid', class: "btn btn-small btn-primary"%>
       <% end %>
       <% if current_user and current_user.is_admin %>
            <%=  link_to "Add contest_series", '/contest_series/new', class: "btn btn-small btn-primary"%>
       <% end %>
       <% if current_user  %>
         <%=  link_to "Download", '/contest_series.csv', class: "btn btn-small btn-primary"%>
       <% end %>
   </div>
</div>


<div id="left_panel">
   <%=render 'layouts/left_panel'%>
</div>
<div id="right_panel">
<div id="right_scroll">
  <%= render 'flash' %>
  <div class="erow"><div class="sectiontitle_bold">Contest:</div></div>

  <table class="places">
    <% if @contest_series then @contest_series.each do |contest_series| %>
      <tr>
        <td>
          <% if current_user and current_user.is_admin %>
             <span title="Click to edit row"><%= link_to image_tag("/assets/pencil_edit.png", :class => 'dock-item'), '/contest_series/'+contest_series.id.to_s+'/edit?referring=index', id:  "editbutton", alt: "Edit"  %></span>
          <% end %>
          <%= link_to contest_series.name, '/contest_series/'+contest_series.id.to_s %>
        </td>
        <td>
            <%= contest_series.start_date %> to <%= contest_series.end_date %>
        </td>
    <% end end %>
  </table>
</div>
</div>

app/views/contest_series/_new.html.erb
<%@submit_button="Create Series"%>
<%= render 'contest_series_form' %>

app/views/contest_series/_show.html.erb
<script> 
   document.getElementById("page_status").innerHTML = '';
</script>
<div id="actionbar" class="span12">
   <div id="crumbs">
     <%=link_to "Home", '/'%>
     &nbsp;--&gt;&nbsp;
     <%=  link_to  "Contest:", '/contest_series'%>
     &nbsp;--&gt;&nbsp;
     <b><%= @contest_series.name %></b>
     </div>
   <div id="controls">
       <% if current_user and current_user.is_admin %>
            <%=  link_to "Edit", '/contest_series/'+@contest_series.id.to_s+'/edit', class: "btn btn-small btn-primary" %>
       <% end %>
       <%=  link_to "Index", "/contest_series", class: "btn btn-small btn-primary" %>
   </div>
</div>
<div id="left_panel">
   <%=render 'layouts/left_panel'%>
</div>

<div id="right_panel">
<div id="right_scroll">
   <%= render 'flash' %>
   <div class="erow" id="name">
      <div class="sectiontitle">
        <%=link_to @contest_series.name, '/contest_series/'+@contest_series.id.to_s %>
      </div>
   </div>
   <div class="erow" id="description">
      <b><i><%= @contest_series.start_date.to_s%> to <%= @contest_series.end_date.to_s%></i></b>
      <p><%= @contest_series.description %></p>
   </div>

   <div class="logs">
      <p>
       <% if @contest_series.is_active then %>
         <%=if @contest_series.xls_log_url and @contest_series.xls_log_url!='' then link_to "Download blank Excel log", @contest_series.xls_log_url, class: "btn btn-small btn-primary" end  %> 
         <%=if @contest_series.odt_log_url and @contest_series.odt_log_url!='' then link_to "Download blank ODS log", @contest_series.odt_log_url, class: "btn btn-small btn-primary" end %> 
         <%=if @contest_series.log_url and @contest_series.log_url!='' then link_to 'View log instructions', @contest_series.log_url else "[No log templates available at this time]" end%></p>
       <% end %>
   </div>
<% if current_user and current_user.is_admin then %>

   <div class="erow" id="log_requirements">
      <div class="rowtitle"><%= "Log requirements:" %></div>
   </div>
   <table>
     <tr>
       <th> QRP vs QRO</th>
       <th> Portable</th>
       <th> Backcountry</th>
       <th> QTH</th>
       <th> RST</th>
       <th> Index</th>
       <th> Frequency</th>
       <th> Per-hour-score</th>
      </tr>
      <tr>
         <td><%=if @contest_series.include_qrp then "Yes" else "no" end%></td>
         <td><%=if @contest_series.include_portable then "Yes" else "no" end%></td>
         <td><%=if @contest_series.include_backcountry then "Yes" else "no" end%></td>
         <td><%=if @contest_series.include_qth then "Yes" else "no" end%></td>
         <td><%=if @contest_series.include_rst then "Yes" else "no" end%></td>
         <td><%=if @contest_series.include_index then "Yes" else "no" end%></td>
         <td><%=if @contest_series.include_freq then "Yes" else "no" end%></td>
         <td><%=if @contest_series.score_per_hour then "Yes" else "no" end%></td>
     </tr>
   </table>

   <div class="erow" id="members_only">
      <div class="rowtitle"><%= "Group Members Only?" %></div>
      <div class="textext"><%= if @contest_series.members_only then "Yes" else "No" end %></div>
   </div>
   <div class="erow" id="email">
      <div class="rowtitle"><%= "Active?" %></div>
      <div class="textext"><%= if @contest_series.is_active then "Yes" else "No" end %></div>
   </div>

<% end %>


   <div class="erow">
      <div class="hrline">
         <hr noshade size="4">
      </div>
   </div>


   <div class="sectiontitle_bold">Contest dates:</div>
   <div class="erow">
     <% if not @contest_series.contests or (@contest_series.contests and @contest_series.contests.count==0) then %>
        <i>No Contests have been added to this series.  Add one!</i></br>
     <% end %>
     <table>
       <% @contest_series.contests.order(:start_time).each do |contest| %>
         <tr>
            <td>
              <% if current_user and current_user.is_admin %>
                <span title="Click to edit row"><%= link_to image_tag("/assets/pencil_edit.png", :class => 'dock-item'), '/contests/'+contest.id.to_s+'/edit?referring=index', id:  "editbutton", alt: "Edit"  %></span>
              <% end %>
               <%=link_to contest.name, "/contests/"+contest.id.to_s %>
            </td>
            <td>
              <%=contest.local_start_date(current_user)%> from <%=contest.local_start_time(current_user)%> to 
              <%=if contest.local_start_date(current_user)!=contest.local_end_date(current_user) then contest.local_end_date(current_user) end%> 
              <%=contest.local_end_time(current_user)%>
            </td>
            <td>
               <%if current_user and @contest_series.is_active then%>
                 <% cl=ContestLog.where(contest_id: contest.id, callsign: current_user.callsign) %>
                 <% if cl and cl.count>0 then %>
                   <%=  link_to "Delete your log", '/contest_logs/'+cl.first.id.to_s+'/delete', class: "btn btn-small btn-primary", confirm: "Delete log: Are you sure?"%>
                   <%=  link_to "Edit your log", "/contest_logs/"+cl.first.id.to_s+"/edit", class: "btn btn-small btn-primary" %>
                 <% else %>
                   <%=  link_to "Add your log", "/contest_logs/new?contest_id="+contest.id.to_s, class: "btn btn-small btn-primary" %>
                   <%=  link_to "Upload Your Log", '/uploads/new?contest_id='+contest.id.to_s, class: "btn btn-small btn-primary" %>

                 <% end %>
               <% elsif @contest_series.is_active then  %>
                 <p><i>Sign in to add your logs</i></p>
               <% end %>
            </td>
         </tr> 
       <% end %>
     </table>
   </div>   


   <% if current_user and current_user.is_admin %>
     <%=  link_to "Add Contest to series", "/contests/new?series_id="+@contest_series.id.to_s, class: "btn btn-small btn-primary btn-highlight" %>
   <% end %>

   <div class="erow">
      <div class="hrline">
         <hr noshade size="4">
      </div>
   </div>
   <div class="erow">
     <div class="sectiontitle_bold">Current scores:</div>
   </div>
   <div class="erow">
     <h2>Total</h2>
     <table style="width:180px">
         <tr>
           <th>Call</th>
 <% @contest_series.contests.order(:start_time).each do |cc| %>
           <th><%=cc.shortname%></th>
 <% end %>
           <th>Total</th>
         </tr>       
       <% @contest_series.callsigns.sort.each do |c| %>
         <tr>
           <td><%=c%></td>
 <% @contest_series.contests.order(:start_time).each do |cc| %>
 <% log_ids = ContestLog.where(:contest_id => cc.id, :callsign => c) %>
 <% if log_ids and log_ids.count>0 then log_id=log_ids.first.id else log_id=nil end%>

           <td><%=if log_id then link_to cc.points(c), "/contest_logs/"+log_id.to_s else cc.points(c) end%></td>
 <% end %>
           <td><%=@contest_series.points(c)%></td>
         </tr>
       <% end %>
     </table> 
   </div>

   <div class="erow">
      <div class="hrline">
         <hr noshade size="4">
      </div>
   </div>

<% if @contest_series.score_per_hour then %>
 <% hour=0; while hour<@contest_series.contests.first.hours do%>
  <div class="erow">
     <h2><%=if hour==0 then "40m+" elsif hour==1 then "80m" end%></h2>
     <table style="width:180px">
         <tr>
           <th>Call</th>
 <% @contest_series.contests.order(:start_time).each do |cc| %>
           <th><%=cc.shortname%></th>
 <% end %>
           <th>Total</th>
         </tr>
       <% @contest_series.callsigns.sort.each do |c| %>
         <tr>
           <td><%=c%></td>
 <% @contest_series.contests.order(:start_time).each do |cc| %>
 <% log_ids = ContestLog.where(:contest_id => cc.id, :callsign => c) %>
 <% if log_ids and log_ids.count>0 then log_id=log_ids.first.id else log_id=nil end%>

           <td><%=if log_id then link_to cc.hour_points(hour,c), "/contest_logs/"+log_id.to_s else cc.points(c) end%></td>
 <% end %>
           <td><%=@contest_series.hour_points(hour,c)%></td>
         </tr>
       <% end %>
     </table>
   </div>

 <% hour=hour+1 %>
   <div class="erow">
      <div class="hrline">
         <hr noshade size="4">
      </div>
   </div>
 <% end %>
<% end %> 


   <div class="erow">
     <div class="sectiontitle_bold">Scoring rules per contact:</div>
   </div>

   <div class="erow">
     <table style="width:270px">
       <tr>
         <td>Base points</td>
         <td><%=@contest_series.base_points.to_s%></td>
       </tr><tr>
         <td>Worked station QRP bonus</td>
         <td>+<%=@contest_series.qrp_points.to_s%></td>
       </tr><tr>
         <td>Your station portable bonus</td>
         <td>+<%=@contest_series.portable_points.to_s%></td>
       </tr><tr>
         <td>Worked station portable bonus</td>
         <td>+<%=@contest_series.portable_points.to_s%></td>
       </tr><tr>
         <td>Your station backcountry bonus</td>
         <td>+<%=@contest_series.backcountry_points.to_s%></td>
       </tr><tr>
         <td>Worked station backcountry bonus</td>
         <td>+<%=@contest_series.backcountry_points.to_s%></td>
       </tr><tr>
         <td>CW bonus</td>
         <td>+<%=@contest_series.cw_points.to_s%></td>
       </tr><tr>
         <td>DX bonus</td>
         <td>+<%=@contest_series.dx_points.to_s%></td>
       </tr><tr>
         <td>Validated contact bonus</td>
         <td>+<%=@contest_series.valid_points.to_s%></td>
       </tr>
     </table>
   </div>
   <div class="erow">
      <div class="hrline">
         <hr noshade size="4">
      </div>
   </div>

</div>
</div>

app/views/contest_series/db_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <action type="<%= @mode %>" sid="<%= @id %>" tid="<%= @tid %>" />
</data>

app/views/contest_series/edit.html.erb
<%= render 'contest_series/edit' %>

app/views/contest_series/editgrid.html.erb
<%= render 'parks/editgrid' %>

app/views/contest_series/editgrid.js.erb
if (window.history.pushState!=null) window.history.pushState(null, '', '/parks/editgrid');
$('#right_panel').html("<%= escape_javascript(render(:partial => 'parks/editgrid')).html_safe %>");

app/views/contest_series/index.html.erb
<%= render 'contest_series/index' %>

app/views/contest_series/new.js.erb
if (window.history.pushState!=null) window.history.pushState(null, 'Huts on the Air', '/contest_series/new');
$('#right_panel').html("<%= escape_javascript(render(:partial => 'contest_series/new')).html_safe %>");

app/views/contest_series/show.html.erb
<%= render 'contest_series/show' %>

app/views/contest_series/show.js.erb
if (window.history.pushState!=null) window.history.pushState(null, '', '/contest_series/<%=params[:id].to_s%>');
$('#right_panel').html("<%= escape_javascript(render(:partial => 'contest_series/show')).html_safe %>");